spring:
 application.name: common
 profiles.active: local
 output.ansi.enabled: detect

---
spring:
  profiles: local

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: test

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: pre

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: pre

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: production

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
