site:
  kuaisan:
    hubei: https://kaijiang.500.com/static/info/kaijiang/xml/hbk3/%s.xml
    anhui: https://kaijiang.500.com/static/info/kaijiang/xml/ahk3/%s.xml
    jiangsu: https://kaijiang.500.com/static/info/kaijiang/xml/jsk3/%s.xml
    guangxi: https://kaijiang.500.com/static/info/kaijiang/xml/gxk3/%s.xml
    neimenggu: https://kaijiang.500.com/static/info/kaijiang/xml/nmgk3/%s.xml
    beijing: https://kaijiang.500.com/static/info/kaijiang/xml/bjk3/%s.xml
    hebei: https://kaijiang.500.com/static/info/kaijiang/xml/hebk3/%s.xml
    shagnhai: https://kaijiang.500.com/static/info/kaijiang/xml/shk3/%s.xml
    gansu: https://kaijiang.500.com/static/info/kaijiang/xml/gsk3/%s.xml
    jilin: https://kaijiang.500.com/static/info/kaijiang/xml/jlk3/%s.xml
