server:
  context-path: /spidert
  #  tomcat:
  #    max-threads: 500
  #    accept-count: 500
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048

spring:
 application.name: spider
 profiles.active: local
 output.ansi.enabled: detect
 profiles:
   include: site

---
spring:
  profiles: local
  #include: site

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

server:
  port: 8080

elaticjob:
  zookeeper:
    server-lists: localhost:2181
    namespace: elastic-job-lite-springboot
  stockJob:
      cron: 0/5 * * * * ?
      shardingTotalCount: 2
      shardingItemParameters: 0=Chengdu0,1=Chengdu1
---
spring:
  profiles: test

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

elaticjob:
  zookeeper:
    server-lists: localhost:2181
    namespace: elastic-job-lite-springboot
  stockJob:
      cron: 0/5 * * * * ?
      shardingTotalCount: 2
      shardingItemParameters: 0=Chengdu0,1=Chengdu1
---
spring:
  profiles: pre

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

---
spring:
  profiles: production

  datasource:
    lottery:
      url: jdbc:mysql://localhost:3306/lottery?useUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
